- fvtr/fvtr.sh
Functionality was added to fvtr.sh in order to make it possible to print logs of tests that failed easily. This was done through the addition of the subcommand "report" to fvtr.sh.
> Made fvtr.sh able to print more detailed errors

- scripts/utilities/update_revision.sh
Gerrit-related features were removed. After updating the revision on the local sources file, the script now:
- Checks connection to GitHub
- Finds out if the sources file with the latest revision has been previously pushed
- Commits and pushes to the user's fork
update_revision.sh now only takes as parameters the sources file path and the user's GitHub account. It is assumed that whoever is running the script is capable of pushing to the advance-toolchain fork of the provided user without any password.
As a side note, I also corrected some typos and weird indentation that were on the original file, but if any of them were intentional please let me know so I can undo what I did.
> Updated update_revision.sh to use GitHub

- utils/install_tools.sh
This patch adds a script with a set of functions to help install and test AT packages.
> Inclusion of install_tools.sh

- scripts/utilities/update_revision.sh
Made the update_revision.sh script automatically add a Signed-off-by
line to commits to GitHub. Also corrected issues with private access
token scope detection.
> Added auto Signed-off-by to update_revision.sh

- scripts/utilities/update_revision.sh
For the automatic revision updates, Cherbot is currently doing amendments to the commits of existing PRs and force pushing, effectively overwriting PRs that we still didn't get a chance to decide whether we should merge or not into our master branch. The proposed changes makes update_revision.sh check if a PR updating a specific package from a specific configset already exists before doing anything, therefore eliminating the described unwanted behavior.
> Stop update_revision.sh from overwriting PRs

- utils/at_downloader/at_downloader.sh
This commit adds the capability to download AT by
selecting a target architecture. It fixes the a
annoying behavior related to download everything
for a specific Linux distribution.
> Add the capability to select the arch of AT for downloading

- configs/10.0/distros/centos-6.mk
- configs/10.0/distros/centos-7.mk
- configs/10.0/distros/ubuntu-16.mk
- configs/6.0/distros/redhat-6.mk
- configs/6.0/distros/suse-11.mk
- configs/7.0/distros/redhat-6.mk
- configs/7.0/distros/suse-11.mk
- configs/7.1/distros/redhat-6.mk
- configs/7.1/distros/redhat-7.mk
- configs/7.1/distros/suse-11.mk
- configs/7.1/distros/ubuntu-14.mk
- configs/8.0/distros/suse-12.mk
- configs/9.0/distros/fedora-22.mk
- configs/9.0/distros/redhat-6.mk
- configs/9.0/distros/redhat-7.mk
- configs/9.0/distros/suse-12.mk
- configs/9.0/distros/ubuntu-14.mk
This commit address the issue #55.
> Add wget as a required dependency for building AT

- Makefile
- configs/9.0/specs/monolithic.spec
Fix where to put the systemd file used by our cache manager mechanism.
> Change cache manager systemd file directory

- fvtr/ck_requires/ck_requires.exp
- scripts/utilities/pkg_build_functions.sh
Currently the list of dependencies for RPM and DEB packages are different, the patches here change the RPM list to be consistent with DEB and fix the ck_requires test to use the new behaviour.
> Change packages dependencies list

- configs/11.0/packages/gcc/stage_2
- configs/11.0/packages/gcc/stage_3
- configs/11.0/packages/gcc/stage_4
- configs/11.0/packages/gcc/stage_optimized
After applying these patches, PR #86 is safe to be merged.
> Work around libsanitizer build issue

- configs/11.0/packages/gdb/sources
Update GDB to version 8.0 on AT 11.0 (Task #108).
> Update GDB on AT 11.0.

- scripts/utilities/update_revision.sh
This patch changes the update_revision script to be able to get the latest
revision from the current branch used in the sources file instead of the
latest revision from the repository.
> Adapt update_revision.sh to get code from branches

- fvtr/speccpu2006/speccpu2006.exp
- fvtr/speccpu2017/at-sniff32.cfg
- fvtr/speccpu2017/at-sniff64.cfg
- fvtr/speccpu2017/speccpu2017.exp
This patch adds the SPEC CPU2017 testsuite to our FVTR.
> [fvtr] Add SPEC CPU2017 to our FVTR

- docs/adv-tool-usage.html
- docs/advtool-faq.html
- docs/advtool-installation.html
This patch updates the AT manual adding information about Environment modules
and the known issues with recent updates.
> Update AT official documentation

- utils/install_tools.sh
This patch changes the install tools script to add the option to update
packages.
> [install_tools] Add option to update packages

- configs/next/distros/redhat-7.mk
- configs/next/distros/suse-12.mk
- configs/next/distros/ubuntu-14.mk
- configs/next/distros/ubuntu-16.mk
> Require autoconf-archive when building AT next

- configs/11.0/specs/monolithic.spec
Required a few packages that are run during installation.
Those packages are part most of the time of minimum distro install
but they could be missing.
Fixes #194 
> Add missing RPM requirements

- configs/next/packages/binutils/sources
Bump to revision 503c367dc237
Closes #606 .
> Update binutils on AT next

- configs/12.0/packages/gdb/sources
Bump to 8.2.0-b37d1b267d24.
Closes #637 .
> Update gdb on AT 12.0

- configs/next/packages/tbb/sources
Bump to version 2019_U1
Bump to revision 4cebdd9a1c9f
> Update tbb on AT next

- configs/next/packages/libhugetlbfs/sources
> Update libhugetlbfs on AT next

- docs/adv-tool-usage.html
- docs/advtool-compiler.html
- docs/advtool-faq.html
- docs/advtool-installation.html
Fix HTML syntax and tags to get rid of errors reported by `tidy`.
> Fix HTML syntax and tags

- .gitignore
- docs/tidy.cfg
As mentioned in issue #649 , the source code is missing a configuration file for tidy.
> Add a tidy configuration file

- docs/adv-tool-usage.html
- docs/advtool-compiler.html
- docs/advtool-faq.html
- docs/advtool-installation.html
Fixed the HTML files so tidy doesn't report anything, meaning the
files pass the validation test.
Fixes #649 
> Update HTML documentation

- configs/12.0/packages/valgrind/sources
Bump to version 3.14.0
Bump to revision 0c701ba2a4b1
Fix #684
>  Update valgrind on AT 12.0

- configs/next/packages/gdb/sources
Bump to version 8.3.50
Bump to revision ca5a17b09eab
Closes #846 
> Update gdb on AT next

- fvtr/fvtr.sh
Fix the script to avoid, for examples, the following lines from the set command:
```
if [ "${MODULES_USE_COMPAT_VERSION:-0}" = '1' ]; then
unset MODULES_USE_COMPAT_VERSION;
MODULES_USE_COMPAT_VERSION=1;
export MODULES_USE_COMPAT_VERSION;
```
This kind of lines produced an awkward output.
Also, remove an old comment from the script with a reference to a file that isn't use any longer.
> Improve fvtr script

- configs/next/deb/monolithic/bionic_dh_change_dest.patch
- configs/next/distros/ubuntu-18.mk
> Add support of Ubuntu 18.04 on next

- configs/11.0/deb/monolithic/stretch_dh_change_dest.patch
- configs/11.0/distros/debian-9.mk
- configs/12.0/deb/monolithic/stretch_dh_change_dest.patch
- configs/12.0/distros/debian-9.mk
> Add support of Debian 9 on AT 11.0 and AT 12.0

- configs/next/distros/redhat-8.mk
- remote-build.exp
- scripts/utilities/pkg_build_rpm.sh
> Add support of RHEL8 on AT next

- configs/next/distros/suse-15.mk
> Add support of SLES 15 on AT next

- configs/11.0/packages/gcc/stage_1
- configs/13.0/deb/monolithic/buster_dh_change_dest.patch
- configs/13.0/distros/debian-10.mk
- configs/next/deb/monolithic/buster_dh_change_dest.patch
- configs/next/distros/debian-10.mk
- scripts/helpers/utilities.mk
> Add support of Debian 10 on AT >= 13.0

- configs/13.0/packages/pveclib/pveclib.mk
- configs/13.0/packages/pveclib/sources
- configs/13.0/packages/pveclib/specfile
- configs/13.0/packages/pveclib/stage_1
- configs/13.0/release_notes/release_notes-body.html
- configs/next/packages/pveclib/pveclib.mk
- configs/next/packages/pveclib/sources
- configs/next/packages/pveclib/specfile
- configs/next/packages/pveclib/stage_1
> Add PVEClib to AT next

- fvtr/pveclib/pveclib.exp
- fvtr/pveclib/test.c
Description in the commit message.
> Add FVTR tests for pveclib

- configs/13.0/packages/gdb/sources
Bump to version 8.3.1
Bump to revision 438a11c8e28c
Close #1144 
> Update gdb on AT 13.0

- scripts/helpers/rsync_and_patch.mk
> fix minor typos

- configs/next/deb/monolithic/focal_dh_change_dest.patch
- configs/next/distros/ubuntu-20.mk
> Add support of Ubuntu 20.04 on AT next

- configs/13.0/packages/gcc/sources
Bump to version 9.3.1
Bump to revision 200e83ac36b7
Close #1414 
> Update gcc on AT 13.0

- configs/next/packages/zlib/sources
> Update zlib optimizations for Power

- utils/install_tools.sh
> Fix install_tools.sh debian package order

- configs/13.0/distros/debian-10.mk
- configs/13.0/distros/redhat-8.mk
- configs/13.0/distros/suse-15.mk
- configs/13.0/distros/ubuntu-18.mk
- configs/14.0/distros/ubuntu-20.mk
> Stop requiring cvs package on AT >= 13.0

- configs/next/packages/tcmalloc/sources
Bump to version 2.8
Bump to revision bda3c82e1161
Close #1573 
> Update tcmalloc on AT next

- configs/13.0/packages/tcmalloc/sources
Bump to version 2.8
Bump to revision bda3c82e1161
Close #1582 
> Update tcmalloc on AT 13.0

- configs/14.0/packages/libhugetlbfs/sources
Bump to version 2.23
Bump to revision 6b126a4d7da9
Close #1682 
> Update libhugetlbfs on AT 14.0

- configs/14.0/packages/glibc/sources
Bump to revision 44c7513a5f55.
Remove unnecessary patch.
> Update glibc on AT 14.0

- scripts/utilities/update_revision.sh
Improve the script that creates our automated pull requests to also add an
'auto' tag to the PR. This will help our CI know which PRs are candidates for
auto-merging in the future.
> Enable auto-merge for automated package update PRs

- fvtr/fvtr.sh
Currently, the current working directory must be `fvtr/` in order to
run `fvtr.sh`.
Change `fvtr.sh` so it can be run from any directory.  All side-effects
remain the same, as output like log files will appear in the same
absolute locations.
> Allow FVTR to be run from anywhere

- Makefile
Stop discarding output sent to stderr and properly forward them to the
same log file used for stdout.
> Fix stderr redirections

- configs/15.0/packages/libdfp/sources
Bump to version 1.0.16
Bump to revision ff629deadfd1
> Update libdfp on AT 15.0

- scripts/helpers/utilities.mk
Building on systems with optimized libraries can conflict with the
AT build.  The loader, including the loader that is built with AT,
will prefer libraries in so-called "optimized" paths.  These are
any paths which are subdirectories of a path in the `ld.so.conf`
configuration which are classified as "optimized" by a predefined
list, generally by processor architecture, like `power9`.
So, a file in `/lib/power9/libc.so` will take preference over
`/opt/atX/lib/libc.so`, even if `/opt/atX/lib` is earlier than
`/lib` in the `ld.so.conf` search order.
The problem coveniently occurs between the two `ldconfig`
stages.  Work around the problem by creating a fake "optimized"
set of libraries which are simply copied from the "unoptimized"
directory into "optimized" subdirectories of a new …
> Enable AT builds on RHEL8

- configs/15.0/packages/libnxz/sources
Bump to version 0.62
Bump to revision e040bcc91e9d
> Update libnxz on AT 15.0

- configs/15.0/packages/binutils/sources
Bump to version 2.37
Bump to revision 2232575acaf0
> Update binutils on AT 15.0

- Makefile
There is no functional change.  The minor changes:
1. There are constructs like:
```
ifneq "$(MAKECMDGOALS)" "clone"
ifneq "$(MAKECMDGOALS)" "edit"
ifneq "$(MAKECMDGOALS)" "pack"
[...lots of unindented code...]
endif
endif
endif
```
The `endif-endif-endif` lines are quite confusing out of context,
especially without indentation.  Add indentation.
Additionally, it is possible to simplify the 3 `ifneq` statements
to a single statement like:
```
ifeq (,$(findstring $(MAKECMDGOALS),clone edit pack))
```
2. There are a few constructs like:
```
ifndef AT_BASE
AT_BASE := [...]
endif
```
Replace these with the simpler:
```
AT_BASE ?= [...]
```
Also, move a couple of comments into better contexts, delete some
unnecessary blank lines, and enforce 4-space indentation.
Signed-off-by: Paul A. Clarke …
> Makefile: minor changes

- configs/15.0/packages/tbb/sources
Bump to version 2021.4.0
Bump to revision df3096075a00
Close #2342 
> Update tbb on AT 15.0

- configs/15.0/packages/binutils/sources
- Remove an unnecessary patch.
- Add patches for issue #2352 .
> Update the list of patches for Binutils on AT 15.0

- configs/13.0/deb/monolithic/control
- configs/13.0/deb/monolithic_cross/control
- configs/13.0/specs/metapkgs.spec
- configs/13.0/specs/monolithic.spec
- configs/13.0/specs/monolithic_at-compat.spec
- configs/13.0/specs/monolithic_compat.spec
- configs/13.0/specs/monolithic_cross.spec
- configs/13.0/specs/release.spec
- configs/14.0/deb/monolithic/control
- configs/14.0/deb/monolithic_cross/control
- configs/14.0/specs/metapkgs.spec
- configs/14.0/specs/monolithic.spec
- configs/14.0/specs/monolithic_at-compat.spec
- configs/14.0/specs/monolithic_compat.spec
- configs/14.0/specs/monolithic_cross.spec
- configs/15.0/deb/monolithic/control
> Fix wording in packages descriptions

- configs/14.0/packages/gcc/sources
Bump to revision fcd6b517c37f
Close #2699 
> Update gcc on AT 14.0

- configs/13.0/release_notes/release_notes-inst.html
- configs/14.0/release_notes/release_notes-inst.html
- docs/advtool-cross-compilers
- docs/advtool-install
Removing failovermethod option from documentation.
> removing failovermethod option from documentation

- configs/next/packages/zlib/sources
Bump to revision 21767c654d31
This new version introduced a new bug (madler/zlib#615), which is
already fixed in the develop branch upstream. So also apply the patch to
fix it.
Close #2776
> Update zlib on AT next

- configs/16.0/packages/gcc/sources
> Move AT 16.0 to GCC branch ibm/gcc-12-branch

- configs/13.0/release_notes/release_notes-body.html
- configs/14.0/release_notes/release_notes-body.html
- docs/advance-toolchain-linux-on-power
- docs/advtool-cross-compilers
- docs/advtool-faq
- docs/advtool-install
- docs/advtool-updates
- docs/advtool-usage
Updated URL tags to open a new window when targeting an external website. Also fixed a couple of incorrect URLs to online documentation.
> Update documentation to pass acrolinx tests.

- configs/16.0/packages/glibc/sources
Bump to revision 2fce85f67c56
Signed-off-by: Cherbot <tcbot@linux.ibm.com>
> Update glibc on AT 16.0

- configs/next/packages/python/python.mk
- configs/next/packages/python/sources
- configs/next/packages/python/stage_optimized
Move AT next to python branch 3.11.
> Update python on AT next

- configs/17.0/packages/zlib/sources
- configs/next/packages/zlib/sources
Bump revisions on AT 17.0 and AT next.
Also get an update of patch from powertechpreview.
Close #3592
> Update zlib on AT >= 17.0

- Makefile
- configs/next/packages/gcc/sources
> Update gcc on AT next

- configs/16.0/packages/libhugetlbfs/sources
- configs/next/packages/libhugetlbfs/sources
- configs/next/packages/libhugetlbfs/stage_1
Bump to revision 1322884fb0d5 on AT next.
Updated patches.
> Update libhugetlbfs on AT >= 16.0

- scripts/utilities/update_revision.sh
This a temporary, auto-merge will be re-enabled once a replacement for AT_Request is found.
> Disable auto-merge PR

- scripts/utilities/update_revision.sh
This reverts commit af7bcf22e887715eb2feb7947481b5c04d689be9.
> Re-enabling the auto-merge option for PR

- configs/15.0/packages/python/sources
Bump to revision 54b5e9e9a8d4
Also update zlib patch to fit with changs in python.
> Update python on AT 15.0

- configs/14.0/packages/python/sources
Bump to revision 5505b91a684b
Also update zlib patch to fit with changs in python.
> Update python on AT 14.0

- configs/14.0/packages/liburcu/sources
- configs/15.0/packages/liburcu/sources
- configs/16.0/packages/liburcu/sources
- configs/17.0/packages/liburcu/sources
- configs/18.0/packages/liburcu/sources
Fixed URLs to get source and documentation.
> Fix URLs for liburcu on AT < next

- Makefile
- scripts/utilities/update_revision.sh
Took advantage to clean the main Makefile and remove outdated call to an auto-update script.
> Remove unused calls to gerrit

- configs/18.0/packages/boost/sources
- configs/18.0/packages/boost/stage_1
> Update boost on AT 18.0

- configs/18.0/packages/python/sources
Bump to version 3.12.10
Bump to revision 310cd8943a57
Replace PR #4351
> Update python on AT 18.0
