advancetoolchain/advance-toolchain

- configs/10.0/packages/python/sources
Updated python to version 3.5.3.
Changes in the patches:
- Removed python-3.5.1-fix_integer_overflow.patch: fix has been merged
into 3.5.3 (see http://bugs.python.org/issue26171);
- New python-3.5.3-getlib64s1.patch rebased old lib64 patch to python
3.5.3.
Signed-off-by: Wainer dos Santos Moschetta <wainersm@linux.vnet.ibm.com>
> Update python for AT 10.0

- fvtr/golang/golang.exp
Golang tests fail miserably if its root directory
does not exist.
Added a check for the directory existence, otherwise
return with error nicely.
Signed-off-by: Wainer dos Santos Moschetta <wainersm@linux.vnet.ibm.com>
> fvtr: check golang directory exists.

- Makefile
- configs/9.0/specs/monolithic.spec
- scripts/utilities/cachemanager.service
- scripts/utilities/pkg_build_rpm.sh
To be able to start watch_ldconfig after the runtime package is installed, this patch sets a systemd service for RPM based distros.
> Use systemd to run watch_ldconfig on RPM based distros

- configs/11.0/packages/binutils/sources
Updates binutils 2.28 to rev f85ae672d555. This fix a binutils
build error due to dynamic relocs (issue #19). Also includes
a patch to fix a incorrect pointer dereference at stabs.c.
Signed-off-by: Rogerio Alves Cardoso <rogealve@br.ibm.com>
> Update binutils 2.28 for AT 11.0.

- docs/advance-toolchain-documentation.html
This patch improves our official documentation page with information about the GitHub repository, IBM power tools, AT Downloader scope, LD_LIBRARY_PATH among other things.
> Improve AT's official documentation

- configs/11.0/packages/boost/sources
This patch updates the version of boost to
1.64.0. It removes the symlink that was
poiting to the file used by AT 10 and adds
a new file called source with the specific
boost configuration for AT 11.0.
> Update boost version on AT 11.0

- configs/11.0/packages/binutils/sources
This commit fixes liburcu not found error detected by urcu test (issue #30)
when cross compile AT 11.0 on X86_64. The error was caused by a incorrect
library path searching on binutils when cross compiled on x86_64.
> Fix liburcu not found error on x86_64.

- remote-build.exp
The script is now capable of copying and building AT on custom directories, through the usage of the optional --dir=<something> parameter.
> Improved remote-build.exp to support custom directories

- Makefile
- configs/9.0/specs/monolithic.spec
In order to be able to uninstall and install the rpm packages without errors on SLES 12 we need to stop using the systemd scriptlets.
> Stop using systemd scriptlets

- configs/11.0/packages/tcmalloc/sources
This patch updates tcmalloc to revision 50125d8 on AT 11.0.
Signed-off-by: Rajalakshmi Srinivasaraghavan  <raji@linux.vnet.ibm.com>
> Update tcmalloc on AT 11.0 (#29)

- configs/10.0/distros/centos-6.mk
- configs/10.0/distros/centos-7.mk
- configs/10.0/distros/ubuntu-16.mk
- configs/8.0/packages/python/stage_1
- configs/9.0/distros/fedora-22.mk
- configs/9.0/distros/redhat-6.mk
- configs/9.0/distros/redhat-7.mk
- configs/9.0/distros/suse-12.mk
- configs/9.0/distros/ubuntu-14.mk
- fvtr/python/python.exp
This commit fixes the issue #45 which is
related to the missing of sqlite3 in the
python version built by AT. It adds the
option --enable-loadable-sqlite-extensions
during the confuration steps and includes
the correct dependency of the devel package
of sqlite for AT8.0 to AT Next.
> Add support for sqlite on AT version of Python

- configs/10.0/packages/binutils/sources
- configs/10.0/packages/gdb/sources
- configs/10.0/packages/glibc/sources
- configs/11.0/packages/binutils/sources
- configs/6.0/packages/glibc/sources
- configs/7.0/packages/glibc/sources
- configs/7.1/packages/binutils/sources
- configs/7.1/packages/gdb/sources
- configs/7.1/packages/glibc/sources
- configs/8.0/packages/binutils/sources
- configs/8.0/packages/gdb/sources
- configs/8.0/packages/glibc/sources
- configs/9.0/packages/binutils/sources
- configs/9.0/packages/gdb/sources
- configs/9.0/packages/glibc/sources
- configs/next/packages/binutils/sources
- configs/next/packages/gcc/sources
- configs/next/packages/gdb/sources
- configs/next/packages/glibc/sources
Git repositories on git.linux.ibm.com don't work anymore, this patch
remove all references to that mirrors.
> Remove git.linux.ibm.com mirrors

- configs/9.0/packages/glibc/stage_2
- configs/9.0/packages/glibc/stage_compat
- configs/9.0/packages/glibc/stage_optimized
This patch removes -Wno-error=array-bounds in glibc for AT 11.0 as it is
not required for newer gcc versions.
Signed-off-by: Rajalakshmi Srinivasaraghavan raji@linux.vnet.ibm.com
> Remove -Wno-error=array-bounds during glibc compilation

- Makefile
- fvtr/ck_ldds/ck_ldds.exp
- remote-build.exp
Fix issue #92.
Canonicalize DESTDIR in Makefile, and tray_dir and destdir in
remote-build.exp in order to avoid unnecessary characters, e.g. multiple
slashes or relative paths.
> Harden path normalization

- scripts/utilities/pkg_build_monolithic.sh
I think this is a common use-case for mindepth, so let's use it.
> Use find -mindepth instead of explicitly excluding "."

- configs/11.0/packages/liburcu/sources
Update Userspace RCU to version 0.9.3 on AT 11.0 (Task #78).
> Update Userspace RCU on AT 11.0

- configs/11.0/packages/valgrind/sources
Update Valgrind to version 3.12.0 on AT 11.0 (task #74).
> Update Valgrind on AT 11.0.

- configs/11.0/packages/tbb/sources
Update TBB to version 2017 Update 6 on AT 11.0 (Task #77). TBB 2017
updates was moved to github. There's no new source packages on the
old link anymore. The old packages 4.3 (2016) are still avaliable.
> Update TBB on AT 11.0.

- configs/11.0/packages/groups
This commit fixes the issue #33  by
fixing the filtering of the files
extensions (.o, .la, .spec and .gox)
which were being added in the runtime
package.
> Fix the file filtering for devel and runtime

- configs/11.0/packages/groups
This patch provides a fix for the issue #79
by removing the Python test files from runtime
and including them into devel packages.
> Remove Python test files from runtime package

- Makefile
- configs/10.0/deb/monolithic/rules
- configs/11.0/deb/monolithic/control
- configs/11.0/deb/monolithic/rules
- configs/11.0/deb/monolithic/runtime.postinst
- configs/7.1/deb/monolithic/rules
- configs/9.0/deb/monolithic/rules
- scripts/utilities/pkg_build_deb.sh
On RPM based distros we use a  a systemd service instead of a cronjob to start our mechanism to automatic update AT's loader cache, these patches does the same for DEB based distros on AT >= 11.0.
> Use systemd in our cache manager system for DEB based distros

- configs/11.0/packages/python/sources
Get a patch for python that fixes SSL errors with recent OpenSSL versions.
Fixes issue #104.
> python: Fix test_ssl error

- configs/11.0/packages/gcc/stage_2
- configs/11.0/packages/gcc/stage_3
- configs/11.0/packages/gcc/stage_4
- configs/11.0/packages/gcc/stage_optimized
Fix for #114    
This commit re-enables libsanitizer on both versions
of AT (native and cross) for versions greater then
11.0. It affects the stages 2, 3, 4 and optimized of
GCC build.
> Re-enable libsanitizer on AT >= 11.0

- Makefile
- configs/10.0/distros/centos-6.mk
- configs/10.0/distros/centos-7.mk
- configs/10.0/distros/ubuntu-16.mk
- configs/11.0/deb/monolithic/rules
- configs/11.0/deb/monolithic/runtime.postinst
- configs/11.0/distros/ubuntu-16.mk
- configs/6.0/distros/redhat-6.mk
- configs/6.0/distros/suse-11.mk
- configs/7.0/distros/redhat-6.mk
- configs/7.0/distros/suse-11.mk
- configs/7.1/distros/redhat-6.mk
- configs/7.1/distros/redhat-7.mk
- configs/7.1/distros/suse-11.mk
- configs/7.1/distros/ubuntu-14.mk
- configs/8.0/distros/suse-12.mk
- configs/9.0/distros/fedora-22.mk
- configs/9.0/distros/redhat-6.mk
- configs/9.0/distros/redhat-7.mk
- configs/9.0/distros/suse-12.mk
- configs/9.0/distros/ubuntu-14.mk
- scripts/helpers/utilities.mk
- scripts/utilities/pkg_build_deb.sh
This patch changes how we choose the mechanism to monitor AT's
loader cache by relying in a variable provided by the distro files.
This fixes the Ubuntu 14.04 build on AT >= 11.0.
> Rely on the distro files to use the systemd service 

- fvtr/ck_requires/ck_requires.exp
- scripts/utilities/pkg_build_functions.sh
We filter the ignored libraries in the RPM dependencies list using the
AT destination, but on cross compiler this doesn't work because it can
generate an empty filter.
> Fix RPM dependencies on cross

- fvtr/package-check/package-check.exp
Fix 2 issues:
- The separator between the package name and version in a deb package
is '_' instead of '-'.  Make the cross-common distro-agnostic.
- There is a package whose flavor doesn't have a second, i.e. just
'cross'.  This package needs its own regular expression.
Fixes issue #134.
> fvtr: fix package-check execution on cross

- Makefile
- configs/11.0/deb/monolithic/rules
- configs/11.0/deb/monolithic/runtime.postinst
- configs/11.0/specs/monolithic.spec
- configs/9.0/specs/monolithic.spec
This patch changes the names of the systemd files to avoid name clash
and work in all environments.
This PR depends on PR #133.
> Systemd fixes

- configs/11.0/distros/centos-6.mk
- configs/11.0/distros/centos-7.mk
- configs/11.0/distros/redhat-7.mk
- configs/11.0/distros/suse-12.mk
- configs/11.0/distros/ubuntu-14.mk
- configs/11.0/distros/ubuntu-16.mk
- configs/11.0/packages/expat/sources
- configs/11.0/packages/expat/stage_1
Update Expat to version 2.2.2 on AT 10.0 and 11.0 to fix CVE-2017-9233 (task #113).
> Update Expat on AT >= 11.0.

- Makefile
- configs/10.0/deb/monolithic/rules
- configs/11.0/deb/monolithic/rules
- configs/11.0/deb/monolithic/runtime.postinst
- configs/11.0/specs/monolithic.spec
- configs/6.0/specs/monolithic.spec
- configs/7.1/deb/monolithic/rules
- configs/8.0/specs/monolithic.spec
- configs/9.0/deb/monolithic/rules
- configs/9.0/specs/monolithic.spec
This patch changes to 644 the mode of the cron file because in some
systems the script doesn't run with 664 permissions.
It also removes the redundancy of the systemd preset file name and
specify the version that the file enables.
Lastly, now the ubuntu packages don't fail in the post install if
the systemd service doesn't start by an unexpected behaviour like
what happens on docker.
This fixes #145 and #132.
Signed-off-by: Raphael Moreira Zinsly <rzinsly@linux.vnet.ibm.com>
> Fixes to the cache manager mechanism

- configs/11.0/packages/glibc/sources
This commit updates glibc for AT 11.0.  Since the upstream branch has
integrated (commit ID c55ad6452e2d) the fix for the malloc warning with
GCC 7 and -O3, this commit also drops the patch from the sources file.
Signed-off-by: Gabriel F. T. Gomes <gftg@linux.vnet.ibm.com>
> Update glibc for AT 11.0

- configs/11.0/packages/gcc/sources
This patch enables GCC's P9 min-max on AT 11.0.
> Re-enable P9 min-max on AT 11.0

- fvtr/ck_provides/ck_provides.exp
This patch fixes the ck_provides FVTR test for DEB based distros and
adapt it to deal with the dummy packages (#23). It also fixes the
check_debs procedure to correctly get the needed packages.
> Fix ck_provides for DEB packages

- configs/11.0/packages/python/sources
This patch changes the fetch of the python's test_ssl fix by getting
the patch from the commit instead of the PR because the md5sum changes
when the PR changes.
> Fix the fetch of Python patches

- fvtr/tbb/par-test.cpp
- fvtr/tbb/tbb.exp
We were not running the parallel test in our TBB test case, this patch
enables it.
> [fvtr] Run TBB parallel test

- configs/next/packages/glibc/sources
This PR removes the patches for -mfloat128 from AT Next.
Tested on Ubuntu 16.04.
> Update glibc on AT Next

- configs/11.0/packages/python/sources
- fvtr/python/python.exp
This patch fixes the failures in our FVTR python test by ignoring
test_pty due to its intermitent failures on the BuildBot environment
and by skiping test_float_with_comma in test_float due to its failures
since glibc's commit ID 70a6707f.
This resolves #146.
> Fix python tests

- configs/10.0/packages/expat/stage_1
- configs/9.0/packages/expat/sources
- configs/9.0/packages/expat/stage_1
Update Expat to version 2.1.1 on AT 9.0 (Issues #148 and #84).
CVE fixes backported:
CVE-2012-6702
CVE-2016-5300
CVE-2016-4472
CVE-2016-0718
CVE-2016-9063
CVE-2017-9233
> Update Expat on AT 9.0.

- configs/9.0/packages/python/sources
Update Python to version 3.4.7 on AT 9.0 (#177).
Signed-off-by: Rogerio Alves <rcardoso@linux.vnet.ibm.com>
> Update Python on AT 9.0.

- scripts/utilities/pkg_build_deb.sh
remake.sh was tripping over existing content in the debhelper
directory.  Clearing that directory before populating it allows
remake to succeed.
> Fix for remake when just building .debs

- configs/next/packages/expat/sources
Commit ID https://github.com/libexpat/libexpat/commit/cb7d430d22c0 on libexpat fixed the dependency check for docbook, which renders obsolete the local patch on AT Next.  This commit removes the local patch and updates libexpat.
> Remove local patch from expat on AT Next

- configs/next/packages/glibc/sources
Commit ID 9d7a3741c9e59eba87fb3ca6b9f979befce07826 on GLIBC updated
elf/get-dynamic-info.h, which requires changes to the patch that removes
the assertions on DT_RPATH and DT_RUNPATH.
Signed-off-by: Gabriel F. T. Gomes <gabriel@inconstante.eti.br>
> Update patch for DT_RUNPATH/DT_RPATH on AT Next

- scripts/utilities/update_revision.sh
This patch changes the update_revision script to fix broken references
to HEAD if the repository goes to a detached one after checkout.
> Check for broken references on update_revision.sh

- configs/11.0/specs/monolithic.spec
- configs/11.0/specs/monolithic_cross.spec
Environment modules are shipped in both cross and non-cross packages, then symlinked in to the system environment modules directory for easy use.  The cross packages were not correctly allowing for installation relocation (via "rpm --prefix"), and the non-cross packages were unnecessarily using RPM_INSTALL_PREFIX (even though they are not relocatable.
Fixes #318 
Signed-off-by:  Paul A. Clarke <pc@us.ibm.com>
> Fix environment modules symlinking

- configs/11.0/specs/monolithic_cross.spec
environment modulefiles are being generated at package creation
time with fixed paths. These static files are incorrect when
an installation is relocated with the "--prefix" option to the
"rpm" install command.
Generate these files dynamically at installation time instead.
Fixes #356
> fix environment modulefiles for prefix installs

- configs/11.0/deb/monolithic/runtime.prerm
- configs/next/deb/monolithic/runtime.prerm
Removes the systemd symlinks for our cache manager system after uninstallation on Ubuntu (#179).
> Properly remove the cache manager services on Ubuntu

- fvtr/oprofile/oprofile.exp
- fvtr/python/python.exp
The Oprofile and Python FVTR testsuites were leaving test files after
the tests runs, this patch ensure they are removed.
This fixes #354.
> fvtr: Remove Oprofile and Python temporary files after testing

- configs/11.0/specs/monolithic.spec
- configs/11.0/specs/monolithic_cross.spec
The final step in a package upgrade is %postun.  This is after
%post for the installation of the new version of the package.
The current %postun will unconditionally remove the files/symlinks
from the system modulefiles directory, thus removing the newly
installed environment modulefiles.  The fix is to move the removal
inside the conditional in %postun, which checks to see if the
current uninstall operation is still leaving an installed
instance of the package on the system.
Fixes #365
> package upgrade will remove new environment modulefiles

- scripts/utilities/update_revision.sh
The automatic update of mpc is not working.  It fails to detect a revision change between what's in configs/next/packages/mpc/sources and what's in mpc's repository.
The failure is due to a wrong comparison operator being used in update-revision.sh
> Use string operator in string comparison

- Makefile
- fvtr/ck_requires/ck_requires.exp
This patch removes output files left by FVTR runs with the clean-fvtr
target, it also renames temporary and output files to maintain a standard.
This addresses #380.
> Do not leave FVTR files after a clean-fvtr

- configs/11.0/deb/monolithic/devel.postinst
- configs/11.0/deb/monolithic_cross/cross-common.postinst
Upgrading common package will fail:
```
Setting up advance-toolchain-at11.0-cross-common (11.0-3) ...
ln: failed to create symbolic link '/usr/share/modules/modulefiles/./at11.0': File exists
dpkg: error processing package advance-toolchain-at11.0-cross-common (--configure):
subprocess installed post-installation script returned error exit status 1
```
Upgrades will call the package's "prerm" script with "upgrade" as the
parameter. Only if the parameter is "remove" will the symlink be removed
which will later be created by the new version's "postinst" script.  Thus,
"ln -s" will fail, as seen here.
Solution is to use "ln -sf" instead.
Fixes #382
> fix "failed to create symbolic link" upgrading common package

- configs/11.0/packages/gcc/stage_4
- configs/11.0/packages/gcc/stage_optimized
The RH BZ #1018072 was fixed and libgo_cv_lib_setcontext_clobbers_tls=no
doesn't need to be set anymore, this patch removes it from the build.
> Remove libgo_cv_lib_setcontext_clobbers_tls=no from GCC build

- configs/8.0/packages/valgrind/sources
The patch allow Valgrind 3.10 to be built with kernel 4.*.
> Take and apply a patch for Valgrind (AT 8.0)

- configs/next/packages/libauxv/libauxv.mk
- configs/next/packages/libauxv/sources
- configs/next/packages/libauxv/specfile
- configs/next/packages/libauxv/stage_1
libauxv became obsolete when glibc 2.16 (AT 6.0) started to distribute
getauxval(), wich provide the same features of libauxv without requiring an
extra project.
Fixes #464.
> Remove libauxv from AT next

- fvtr/python/python.exp
The time spent on python tests increased from ~3 minutes to ~60 minutes
after updating it to version 3.6.
This increase is related to tests test_multiprocessing_fork,
test_multiprocessing_forkserver and  test_multiprocessing_spawn.
> Disable 3 python tests on python >= 3.6

- fvtr/speccpu2006/at10.0-sniff32.cfg
- fvtr/speccpu2006/at10.0-sniff64.cfg
Fix #549.
(EDIT: Tested on a SLES 12 powerpc64le server)
> Fix SPEC CPU2006 config file for AT 12.0 (GCC 8)

- configs/11.0/packages/oprofile/sources
Backport 2 patches from Oprofile master branch in order to fix issues on
POWER9.
Fixes issue #499.
> Backport patches to Oprofile on AT 11.0

- scripts/helpers/utilities.mk
On RedHat/SuSE, the list is made of package name+version.
However, on Ubuntu/Debian the list was made only of package name.
This meant a version requirement, like make-[4-9], made the check
failed while comparing with the list of package name only.
Fixes #570 
> Fix the list of packages to compare requirements with

- fvtr/ck_ldds/ck_ldds.exp
Debug files may not have information about the interpreter and can be
safely ignored when validating the interpreter.
Fixes issue #573.
> Do not check the interpreter of debug files in ck_ldds

- configs/12.0/packages/golang/sources
Get revision 3d5958383663.
Closes #572.
> Update golang to 1.10 on AT >= 12.0

- configs/9.0/packages/glibc/stage_1
Avoid random build failures by serializing locale generation.
This patch may increase build time by 5 minutes.
> Serialize locale generation for AT >= 9.0

- configs/11.0/packages/gcc/stage_4
GCC libraries were missing debug information, particularly libgo.
> Build GCC libraries with debug information on AT >= 11.0

- fvtr/python/python.exp
Description in the commit message.
> Disable test_signal and test_epoll in Python's FVTR

- scripts/utilities/update_revision.sh
In update_revision.sh, a ssh test to github.com was troubleshooting
with stdin. This caused an issue with a calling script, that got
unexpected EOF.
To avoid that issue, ssh gets /dev/null as stdin for the test to
github.com.
> Scripts: fix ssh call

- configs/10.0/packages/valgrind/stage_1
Add the make target `man-pages` to the `stage1` script of Valgrind. This will generate the missing manpages.
Fixes #767
> Generate manpages for Valgrind on AT >= 10.0

- configs/next/packages/valgrind/sources
- fvtr/valgrind/valgrind.exp
Bump to revision de7fc1a0593c
In addition it takes a newer itrace tarball including an update to fit with a change in Makefile.am in valgrind and it uses an updated test of valgrind.
Closes #823 
> Update valgrind on AT next

- fvtr/ck_lock_elision/tle_supported.c
The test is ignored if the kernel doesn't support htm-nosc.
> Fix ck_lock_elision test

- configs/11.0/distros/redhat-7.mk
- configs/11.0/distros/suse-12.mk
- configs/11.0/distros/ubuntu-14.mk
- configs/11.0/distros/ubuntu-16.mk
- configs/11.0/packages/glibc/stage_2
- configs/12.0/distros/redhat-7.mk
- configs/12.0/distros/suse-12.mk
- configs/12.0/distros/ubuntu-16.mk
- configs/next/distros/redhat-7.mk
- configs/next/distros/suse-12.mk
- configs/next/distros/ubuntu-16.mk
- configs/next/distros/ubuntu-18.mk
- fvtr/systemtap/systemtap.exp
Added the package to requirement on AT 11.0, 12.0 and next.
Enabled systemptap when building glibc.
Fix #946 
> Add the package systemtap-sdt-dev to requirements

- fvtr/python/python.exp
In order for the FVTR to work, we need reliable tests.
Unfortunately, some of the python tests have been failing
intermittently, making it difficult to trust the entire python
FVTR test.
In order to improve this situation, this patch excludes the following
python tests from the FVTR:
- test_faulthandler
- test_imaplib
- test_selectors
- test_time
> Excludes even more python tests in the FVTR

- configs/11.0/packages/glibc/stage_1
- configs/11.0/packages/glibc/stage_2
- fvtr/systemtap/systemtap.exp
Replaces the previous code that enabled systemtap probes in glibc with a
new one that copies the header files to the build directory.
This has the advantage of allowing 2 builds (e.g. 32 and 64 bits) to
execute at the same time because each build has its own copy of the
header files.  Its removal will not break the other build.
This is also refactoring the FVTR testcase in order to improve the log
output and to guarantee the test will check both 32 and 64 bit libraries
when necessary.
Related to issue #946.
> Refactor code for enabling systemtap probes in glibc

- configs/13.0/packages/glibc/sources
glibc 2.30 has been released and will be distributed on AT 13.0.
AT next will continue to track glibc master branch.
> Diverge glibc on AT 13.0 from AT next

- configs/13.0/packages/pveclib/pveclib.mk
- configs/13.0/packages/pveclib/stage_1
Added -mcpu=power8 to build on ppc64 64 bits.
Dropped the 32 bits build as __int128 is not supported on this target.
> Fix pveclib build on ppc64

- utils/install_tools.sh
When building AT next, the packages have the next version of AT in their name,
not "next". So, when the installation tool installs those packages it fails
because of this mistmatch.
The installation tool has been updated to find the AT next packages.
This is part of a request to build AT next on a weekly basis.
> Allow the installation tool to install AT next packages

- docs/advtool-compiler.html
- docs/advtool-installation.html
IBM FTP has been the new repository for AT packages since a few weeks.
The links to Unicamp FTP server need to been replaced with links to the
IBM FTP server.
> Replace links to Unicamp with links to IBM

- configs/10.0/packages/glibc/sources
Get and apply a patch to fix CVE-2018-6551 related with glibc.
The patch fixes glibc 2.24 provided by AT 10.0.
The fix has been provided upstream since glibc 2.28 (AT >= 12.0).
The fix was backported upstream for the following versions of glibc:
- 2.22 (AT 9.0)
- 2.26 (AT 11.0)
Fix #567 
> Fix CVE on glibc 2.24 on AT 10.0

- fvtr/python/python.exp
In order for the FVTR to work, we need reliable tests.
Unfortunately, some of the python tests have been failing intermittently,
making it difficult to trust the entire python FVTR test.
In order to improve this situation, this patch excludes the following
python tests from the FVTR:
- test_asyncgen
- test_logging
- test_poplib
- test_threading
> Exclude more python tests in the FVTR

- configs/10.0/packages/gcc/stage_2
- configs/11.0/packages/gcc/stage_2
This commit fixes a bug introduzed in:
commit: 2273ba38d8a493018e3ab63dc96ea7376e2cd3d0
subject: Fix: Mixing AT and host env during gcc build stages
Whilst explicitly setting the loader the linker should set for generated
ELFs, I was used the  wrong path and name for the loader in ppc and
ppc64 arquitectures (so, only working on ppc64le).
Signed-off-by: Raoni Fassina Firmino <raoni@linux.ibm.com>
-----------------------------------------------------------------------------------------
More about the bug/fix here:
https://github.com/advancetoolchain/advance-toolchain/pull/1149#discussion_r336489887
> Fix gcc_2 build with wrong loader name for ppc and ppc64

- docs/adv-tool-usage.html
- docs/advtool-installation.html
As AT 10.0 is no longer supported, updated the documentation to remove the
AT 10.0 column from the installation html file. Side effect, it removed
Debian 8 and Ubuntu 14.04 entries.
Also updated the optimization entry in usage html file.
> Remove AT10.0 from install documentation

- configs/13.0/packages/gcc/sources
- configs/next/packages/gcc/sources
Updated the URL to libssp patch for gcc on AT >= 13.0.
> Update gcc patch commit on AT >= 13.0

- configs/11.0/packages/gcc/stage_1
- configs/next/packages/gcc/stage_1
At stage 1 of gcc, it checks we are using an IBM branch (if not it ends the build) and then updates gcc/REVISION as shown in the following example:
from: `[ibm/gcc-9-branch revision 277354]`
to: `[ibm/gcc-9-branch revision 277364, based upon FSF revision 277354]`
Removed unreacheable code from AT next stage 1.
Close #738
> Fix display of gcc -v on AT >= 11.0

- configs/next/packages/gcc/sources
Bump to version 10.0.1
Bump to revision bcf3fa7cf5a3
The patch related with libssp was updated.
Close #1266 
> Update gcc on AT next

- configs/13.0/distros/redhat-8.mk
- configs/13.0/packages/gcc/sources
- configs/next/packages/gcc/sources
The `fixincludes` step performed during GCC compilation is currently fixing system headers from `/usr/include`, rather than from `<at-build-dir>/opt/*`. This can cause problems due to a mismatch between header versions installed in the system and the ones used by AT. The commit messages have more detail about it.
This problem is likely due to some missing/wrong GCC configuration or by the way `--with-advance-toolchain` flag works. I'm still investigating the root cause.
Meanwhile, I'm adding a hotfix to just skip the specific fix from `fixincludes` that causes the problem (see commit msg to understand why this is OK).
I'm also removing the requirement for `qt5-devel` on RHEL8, as it is not necessary.
> Fix AT >= 13.0 builds on RHEL8

- configs/13.0/packages/python/stage_1
- fvtr/python/python.exp
After a recent change, Python ended up not recognizing the OpenSSL
headers from AT.
So, it's now necessary to specify where the OpenSSL headers and
libraries are available at configure time.
This also adds an extra test to guarantee the module will always be
enabled.
Fixes #1269 .
> Enable Python's SSL module on AT >= 13.0

- scripts/utilities/update_revision.sh
When checking what was the latest git commit id of a given repository, more than one branch name could be returned. In this case the given repository is skipped.
The current patch ignores users branches that could be found (we only want
official branches). Despite this change, if more than one branch is found,
a proper warning will be printed.
> Avoid users branches in update_revision.sh

- scripts/utilities/update_revision.sh
This improves commit id 2d381dfdd33c8361ab53bc51b775d310368cd05f.
It ignores branches based on a list of keywords.
> Improve fix of update_revision.sh

- configs/next/packages/python/sources
Bump to revision 5157506e043f
The bump includes a commit that causes conflicts with one of the
patches we apply for AT. This commit also changes that patch to a
newer version to overcome those.
Supersedes #1326
> Update python on AT next

- configs/next/packages/python/stage_1
On AT next, enabling the flags to build python in an optimized way.
> Enable python optimizations flags on AT next

- configs/next/packages/zlib/sources
There was a recent effort to optimize some hot functions from zlib
to increase its performance on Power processors. Patch sets have
already been sent to the community to optimize the following functions:
- longest_match
- slide_hash
- adler32
- crc32
Performance tests show considerable improvements on compression and
decompression throughputs, ranging from 4% up to 160%.
As of now, all patches have already been waiting reviews for a few
months, without any indication that this will happen any time soon.
This commit incorporates those optimizations in the zlib package
distributed with AT as out-of-tree patches while they are not
integrated upstream.
> Add zlib optimizations for Power

- configs/13.0/distros/redhat-8.mk
The requirement for qt5-devel on RHEL8 builds had been temporarily
lifted due to a problem on our build server. This problem has been fixed
and so the requirement should be added back again.
Closes #1270
> Re-add qt5-devel requirement on RHEL8

- remote-build.exp
`remote-build.exp` currently presumes that the user's
local home directory is the same as the user's directory
on the remote host. So, if the local home is, say,
/home/user and the remote home is, say, /home2/user,
and a HOME-relative directory is chosen for the "tray"
or the "destination" (which is the default), the build
will fail.
Accommodate different remote HOME directories by
deferring the determination of dependent variables
until the remote HOME directory can be retreived
and prepended appropriately.
Fixes #1282
> Accommodate hosts with different HOME directories

- remote-build.exp
Previous commit for issue #1282 can be flaky if there is a fair amount
of text after logging in and before the first command can be executed.
Flushing this data before executing that first command is essential.
Fixes #1282.
> Fix remote-build.exp remote-home commit

- configs/14.0/deb/monolithic/control
- configs/14.0/deb/monolithic_cross/control
- utils/install_tools.sh
Fixed the rules that create the deb packages.
Fixed the script that installs libnxz deb/rpm packages.
> Fix libnxz deb on AT >= 14.0

- configs/14.0/packages/binutils/stage_1
- configs/14.0/packages/binutils/stage_2
- configs/14.0/packages/binutils/stage_3
- configs/next/packages/gdb/stage_1
- fvtr/ck_binaries/ck_binaries.exp
Binutils has recently changed its build environment and moved gdbserver
to the root directory.  Now, gdbserver is built by default causing a
conflict with the gdbserver build with gdb.
> Disable gdbserver build on Binutils

- scripts/distributed/at-create-ibmcmp-cfg.sh
`at-create-ibmcmp-cfg.sh` invokes `xlc_configure -at`.
Without specifying the AT version, only "supported" versions
of AT are found by `xlc_configure`, and current versions
of XL C/C++ only support AT 8, 9, 10, and 11.  AT versions
12 and 13 will report an error at install or upgrade, or
when manually attempting to generate the configuration files:
```
$ /usr/bin/sudo /opt/at13.0/scripts/at-create-ibmcmp-cfg.sh
Testing for optional IBM XL compilers installation...
This will check for XLC/XLF availability and create config files for them in /opt/at13.0/scripts
IBM XL compilers found in /opt/ibm
File /opt/at13.0/scripts/xlC-16_1_1-AT13_0.dfp.cfg already exists. Recreating it!
/opt/ibm/xlC/16.1.1/bin/xlc_configure -gcc /opt/at13.0 -o /opt/at13.0/scripts/xlC-16_1_1-AT13_0.dfp.cfg …
```
> Fix at-create-ibmcmp-cfg.sh for recent AT versions

- docs/advtool-compiler.html
- docs/advtool-installation.html
Ubuntu 20.04 starts to complain about ftp:// links.
Replacing ftp:// links with https:// links as public.dhe.ibm.com supports it.
Fix #1544 
> Replace ftp:// links with https:// links in doc

- configs/14.0/deb/monolithic/control
- configs/14.0/deb/monolithic/libnxz-dbg.postinst
- configs/14.0/deb/monolithic/libnxz.postinst
- configs/14.0/deb/monolithic/libnxz.postrm
- configs/14.0/deb/monolithic_cross/control
- scripts/utilities/pkg_build_deb.sh
The package advance-toolchain-libnxz provided the same files as the package
advance-toolchain-<AT version>-libnxz leading to an error when installing
the packages.
Fix #1553 
> Fix libnxz deb packages

- remote-build.exp
`remote-build.exp` checks for `screen`, and will fallback to `tmux`
if not found.  The `expect` check runs `which screen` and looks for
either "no screen" or a command prompt.  Unfortunately, the command
prompt will always be displayed after `which screen`, regardless of
whether `screen` was found:
```
$ which screen
/usr/bin/screen
$
```
```
$ which screen
which: no screen in (/home/user/bin:/usr/bin:/usr/sbin)
$
```
The result of the `expect` check is fragile, sometimes detecting
the prompt first, and assuming `screen` was found, when it wasn't.
Harden this check by looking for either "no screen" or "/screen".
> remote-build.exp: harden check for `screen`

- fvtr/ck_binaries/ck_binaries.exp
The binary gdbserver is only available on native builds and should not
be checked on cross compilers.
Fixes: 2781f58f58d5 ("Disable gdbserver build on Binutils")
Fixes #1552.
> Stop checking for binary gdbserver on cross compiler

- configs/14.0/deb/monolithic/control
- configs/14.0/deb/monolithic_cross/control
- configs/14.0/packages/binutils/binutils.mk
- configs/14.0/release_notes/release_notes-body.html
- configs/14.0/specs/metapkgs.spec
- configs/14.0/specs/monolithic.spec
- configs/14.0/specs/monolithic_at-compat.spec
- configs/14.0/specs/monolithic_compat.spec
- configs/14.0/specs/monolithic_cross.spec
OProfile has been removed from AT14, but some mentions remain.
Remove those.
- Package descriptions (required replacement of symlinks with files)
- Release Notes license summary
- Creation of "oprofile" user at install time
- Removing the "binutils_3" target from `binutils.mk`, per the leading comment:
```
```
> Remove last vestiges of OProfile

- configs/14.0/deb/monolithic/devel-dbg.postrm
- configs/14.0/deb/monolithic/mcore-libs-dbg.postrm
- configs/14.0/deb/monolithic/perf-dbg.postrm
- configs/14.0/deb/monolithic/runtime-dbg.postrm
- configs/14.0/specs/monolithic.spec
- configs/9.0/deb/monolithic/mcore-libs-dbg.postinst
- configs/9.0/deb/monolithic/perf-dbg.postinst
- configs/9.0/deb/monolithic/runtime-dbg.postinst
- fvtr/perf/perf.exp
The debuginfo packages are not usable by the `perf` command, since
for a library `/opt/at{version}/lib64/libA.so.0`, perf looks for
`/opt/at{version}/lib64/.debug/libA-{libversion}.so`, resulting in:
```
$ perf probe -v -x /opt/at13.0/lib64/libpthread.so.0 --add 'pthread_mutex_trylock%return $retval'
[...]
Could not open debuginfo. Try to use symbols.
[...]
```
AT currently creates symlinks for
`/opt/at{version}/lib64/.debug/libA-{libversion}.so.debug`
to point to the actual debuginfo file, but not for
`/opt/at{version}/lib64/.debug/libA-{libversion}.so`
Adding the latter, as this patch does, results in:
```
$ perf probe -v -x /opt/at13.0/lib64/libpthread.so.0 --add 'pthread_mutex_trylock%return $retval'
[...]
Open Debuginfo file: /opt/at13.0/lib64/.debug/libpthread-2.30.so
Try to find …
```
> Make debuginfo usable by `perf`

- remote-build.exp
- scripts/helpers/pack-exclude.lst
Commit 60c6a74bbd577012229ff50acc8db2d22b5661d6 subtlely changed the
`DESTDIR` used by `./remote_build.exp`, leaving a trailing `/` in some
cases, including the default case.  The results were mostly innocuous,
but the FVTR test `ck_ldds` failed, e.g.:
```
ck_ldds: power8:  The interpreter of /home/pc/opt/at14.0-0-alpha2/lib64/libpaf-dsc.so.0.0.3 is not  canonical: /home/pc/opt//at14.0-0-alpha2/lib64/ld64.so.2
```
Fix this by removing any trailing `/` characters from the associated
variables.
Note that the code before the above commit was using the Tcl command
`file canonicalize`, but that no longer works because the paths
being manipulated are from the target build system, and may not be
valid paths on the system running the `remote-build.exp` script.
Also, commit …
> Fix-ups in `remote-build.exp`

- Makefile
- scripts/skeletons/prefetch_target.mk
This is a subjective change, but I believe messages for long-running
tasks should always be timestamped as a best practice. Timestamps can
be diagnotic as well, if a build takes extra time, the culprit phase
can be found quickly.
The chosen format of the timestamp matches that already chosen for
the collected logs.
Sample output:
```
2020-07-30_01.59.31 Completed binutils copy!
2020-07-30_01.59.31 Applying patches to binutils...
2020-07-30_01.59.31 Applied patches to binutils!
2020-07-30_01.59.31 Starting the build of binutils_1...
```
Also, sneaking in two tiny changes:
- Combine two lines which are, together, a single `find` command.
- Spell-o
> Add prefix timestamps to build messages

- configs/12.0/deb/monolithic/control
- configs/12.0/deb/monolithic_cross/control
- configs/13.0/deb/monolithic/control
- configs/14.0/deb/monolithic/control
- configs/14.0/deb/monolithic_cross/control
Replaced deprecated value, `extra`, of the priority entry in control files.
According to [Debian Policy Manual](https://www.debian.org/doc/debian-policy/ch-archive.html#s-priorities), the `optional` value should be used instead of `extra`.
Fix #1564
> Update priority entry of deb packages

- configs/13.0/deb/monolithic/rules
- configs/13.0/deb/monolithic_cross/rules
- configs/14.0/deb/monolithic/rules
Added a call to `dh_missing --fail-missing` after `dh_install`.
This avoids warnings when generation deb packages as `dh_install --fail-missing` has been deprecated.
Fix #1599
> Improve rules files

- docs/advtool-compiler.html
- docs/advtool-installation.html
Commit d223471cf977202ec13faefee916d96b5a8ace79 "Remove references in the
website to unsupported distributions", including "Red Hat 6", but missed
a few notes.  Remove these, too.
Also, update the "current" Ubuntu release in the documentation, and
remove Debian 8.
> Remove vestiges of Red Hat 6, Ubuntu 14.04, Ubuntu 14.10, and Debian 8

- configs/11.0/specs/monolithic.spec
- configs/14.0/specs/monolithic.spec
- configs/14.0/specs/monolithic_compat.spec
With POWER10, string comparisons do not work as expected between POWER
processors anymore, e.g. "10" < "8".
This patch replaces simple string comparisons with `sort -V`.
Closes issue #1670 .
> Fix the test for minimum processor during RPM installation

- configs/next/packages/gcc/sources
Commit ac39da6 added an off-tree patch to fix a GCC issue when
building libgo for Power10. At the time, the patch was under review
on gcc-patches. Now it has been merged upstream as 199baa71f7a6c, so we
don't need to apply it anymore. Let's stop applying the patch now,
otherwise the next Cherbot GCC bump will fail.
> Stop applying libgo fix to gcc on AT next

- configs/14.0/packages/glibc/sources
This patch is still under review in libc-alpha, but I think it's
important to get it in AT 14.0-1 before it's accepted upstream.
> Implement TLS on PC-rel in glibc

- configs/11.0/packages/python/sources
Update to Python 3.6.12, from version 3.6.6.
This update requires changes to the lib64 patch and also requires a
patch that is used on earlier AT versions in order to ignore a test for
the zlib version.
> Update Python on AT 11.0 and 12.0

- configs/next/packages/gcc/gcc.mk
- configs/next/packages/gcc/stage_2
- configs/next/packages/gcc/stage_3
A while ago, both GCC and glibc received changes that allowed to build
glibc early, immediately after the first GCC build.  See the difference
between AT 7.0 and 7.1.
This modification allowed AT to remove either GCC's stage 2 or stage 3
and provide the same feature-complete GCC that stage 3 provides.
> Remove GCC stage 2 from AT next

- fvtr/python/python.exp
Some Python tests have been unreliable on AT <= 12.0.
test_distutils is known to fail when run from the install directory.
> Disable more Python tests on AT <= 12.0

- configs/next/deb/monolithic/control
- fvtr/ck_provides/ck_provides.exp
5 of our deb packages have a Pre-Depends relationship because their
postinst(configure) execution depend on the availability of ldconfig.
However, many other packages had a Pre-Depends relationship without
having a pre-configure dependency.
> Remove most pre-dependencies on deb packages

- configs/12.0/packages/zlib/sources
The previous patch to add zlib optimizations was applying them also to 32-bit
targets, but some optimizations are only intended for 64 bits. The updated patch
makes sure optimizations are only applied to 64-bit targets.
This issue impacted AT12's 32-bit builds, which should be fixed now.
> Update zlib patch

- fvtr/ck_binaries/ck_binaries.exp
Older AT releases supported both ppc and ppc64.  For those releases,
some executables or symlinks were provided in order to simplify usage.
These executables used to have 2 different prefixes:
- Target-based, e.g. powerpc64-linux-gnu-readelf;
- Alternative, e.g. powerpc-linux-gnu-readelf.
However, not all executables available as target-based also had an
alternative-based prefix.  gdb is an exception and is only available as
a target-based prefix.
Futhermore, this issue is not reproduced on AT >= 13.0 because these
versions do not support big-endian targets anymore.
This commit is also improving verbosity of the test showing more
executables that were tested.
Fixes: 2781f58f58d545115ab40bddabcb6b5bbf82ae16
> Fix gdb check on AT <= 12.0

- scripts/utilities/update_revision.sh
A check about branch could lead to the master branch whereas the branch
to check isn't related to it.
This `expr index "${branch}" "HEAD"` checks that any chars in `"HEAD"` is found
in `"${branch}"`. And if so, set the reference branch to `"HEAD"`.
This means if `"${branch}"` is `"VALGRIND_3_16_BRANCH"`, the reference branch will
be `"HEAD"`, which is incorrect.
Updated the check to ensure the whole word `"HEAD"` is found or not in `"${branch}"`.
> Improve script that updates revisions

- configs/next/packages/python/sources
- configs/next/packages/python/stage_1
- fvtr/gdb/gdb.exp
- fvtr/python/python.exp
This PR includes a fix for Python FVTR tests on AT next, an update to Python 3.9 on AT next and a few changes in the way we distribute Python. Copying the commit message of the most relevant commit:
Python 3.9 has been recently released and is the version that should be
followed by AT 15 (current AT next). While updating the revision, I took the
time to fully revise all patches we have been applying to Python and actually
found out we don't need two of them anymore (with a catch).
1) Patch to skip test_ssl.test_random_fork:
This was needed back in 2017 due to a bug in OpenSSL 1.1.1c (see discussion
and linked Python issues in [0]). This has been fixed upstream a long time
ago, and AT next currently follows OpenSSL 1.1.1h, which already includes
the fix.
2) Patch to update Python's lib …
> Follow Python 3.9 on AT next

- fvtr/ck_gold/ck_gold.exp
- fvtr/ck_lock_elision/ck_lock_elision.exp
- fvtr/ck_provides/ck_provides.exp
- fvtr/ck_tuned/ck_tuned.exp
- fvtr/gccgo/gccgo.exp
- fvtr/gdb/gdb.exp
- fvtr/oprofile/oprofile.exp
- fvtr/python/python.exp
- fvtr/shared.exp
- fvtr/speccpu2006/speccpu2006.exp
This PR fixes almost all issues from #1813.  The only one missing is the perf setup on the build servers. It also skips `test_strptime` Python test on AT < 11. The test is broken prior to Python AT 3.6 and caused some failures on test builds.
Please check the commit messages for more info.
This is the FVTR output on the same host as in #1813, with this PR (+ proper perf setup):
```
2020-11-19_17.38.37 Running FVTR for at15.0-0-alpha...
amino                   power8:         ignored
boost                   power8:         passed
ck_binaries             power8:         passed
ck_gold                 power8:         passed
ck_ldconfig             power8:         passed
ck_ldds                 power8:         passed
ck_libbits              power8:         passed
ck_lock_elision …
```
> Fix FVTR tests being wrongly ignored on AT next

- fvtr/perf/perf.exp
It doesn't make much sense to run the perf FVTR test on cross builds, since it
won't run on a Power machine using AT.
> fvtr: Skip perf test on cross builds

- configs/13.0/packages/python/sources
Bump to the tag v3.7.9.
Fixes #1889 and #1890.
> Update python on AT 13.0

- scripts/utilities/update_revision.sh
After commit 8607a59, the script wasn't able to get updates from HEAD branch
of packages because it tried to get refs/heads/HEAD instead of HEAD.
Fix #1897
> Fix update_revision.sh to get updates from HEAD

- configs/14.0/packages/gcc/sources
- configs/14.0/packages/glibc/sources
This updates GCC on AT 14, fixes the libssp patch and also updates the URL to the glibc TLS patch to avoid md5sum mismatches if the file from patchwork gets changed (which just happened recently).
Closes #1900
> Update GCC on AT 14 plus fixes

- scripts/utilities/update_revision.sh
Apparently curl has changed the way it returns the status code, from
adding a header-like line with 'Status: $code $description' to a
single line at the top of the output like 'HTTP/$version $code'.
This commit makes the necessary adjustments to update_revision.sh to
handle this transition, and should work with older versions of curl as
well.
#1952 was created using the updated script.
> Handle new curl formatting for status codes on package update script

- configs/next/packages/gcc/sources
GCC 11 defaults to DWARF5. This causes problems with tools that are not
ready for it.  In particular, `perf` on SLES 15 SP2:
```
$rpm -qi perf
Name        : perf
Version     : 5.3.18
Release     : 23.24
```
Pull request #1928 hit this issue, seeing the FVTR test for `perf`
hang at the command:
```
$ perf probe -v -x /path/to/AT/at-next-15.0-0-alpha/bin/ld test_perf_debug=main argc
probe-definition(0): test_perf_debug=main argc
symbol:main file:(null) line:0 offset:0 return:0 lazy:(null)
parsing arg: argc into argc
1 arguments
Open Debuginfo file: /path/to/AT/at-next-15.0-0-alpha/bin/ld
Try to find probe point from debuginfo.
```
Revert the subject patch at least until these tools are ready.
Fixes #1951
> [next] Revert GCC 11 'Default to DWARF5'

- scripts/utilities/check_versions.sh
New script that compares the upstream version number with the version number
stored in the given sources file.
> Add a script to check upstream version

- configs/next/deb/monolithic/rules
- configs/next/deb/monolithic_cross/rules
- configs/next/packages/gcc/sources
- configs/next/packages/glibc/sources
- scripts/distributed/find_dependencies.sh
This is still a draft
I still need to test this on RHEL and SUSE yet. Works on Debian.
For this to work we need to apply the patch bellow on gcc.
```
diff --git a/gcc/config.gcc b/gcc/config.gcc
index 17fea83b2e4..6827b799dc6 100644
--- a/gcc/config.gcc
+++ b/gcc/config.gcc
@@ -5071,16 +5071,6 @@ case "${target}" in
(at="/opt/$with_advance_toolchain"
echo "/* Use Advance Toolchain $at */"
echo
-                        echo "#undef  LINK_OS_EXTRA_SPEC32"
-                        echo "#define LINK_OS_EXTRA_SPEC32" \
-                             "\"%(link_os_new_dtags)" \
-                             "-rpath $prefix/lib -rpath $at/lib\""
-                        echo
-                        echo "#undef  LINK_OS_EXTRA_SPEC64"
-                        echo "#define LINK_OS_EXTRA_SPEC64" \ …
```
> Fix next to work without RUNPATH on binaries

- configs/14.0/specs/monolithic.spec
The main loop of the postinst scriptlet of the runtime-debuginfo package
wasn't properly closed.
Added an end to the loop.
> Fix postinst scriptlet on AT >= 14.0

- configs/13.0/specs/monolithic.spec
Applied part of fa9b20769b2e on AT 13.0 to allow the `perf` test to pass.
> Make debuginfo usable by `perf` on AT 13.0

- configs/next/packages/binutils/stage_2
Since [c46b706620eb](https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=c46b706620eb), binutils has provided the option follow-debug-links (enabled by default).
This has been included in AT with commit c8efa1662541.
Since that, the tests `ck_ldds` and `systemtap` have failed when ran against the AT packages.
Disabling the option to allow the tests to pass.
> Disable follow-debug-links in binutils on AT next

- fvtr/perf/perf.exp
The perf FVTR test tried to set a probe point using an existing name.
The probe point used by the test is fixed, so if a previous invocation
of the same test was interrupted, the probe point could remain causing
future invocations to fail.
Use a name for the probe point which is much less likely to encounter
such a conflict by appending the process ID.
Fixes #2047
> FVTR perf: Append process ID to perf probe event

- configs/13.0/specs/monolithic.spec
- configs/14.0/specs/monolithic.spec
Fixed usage of `systemctl` in postinstall scriptlet of `runtime` rpm by removing the option `--no-reload` when using the `preset` command.
Based on the [documentation](https://www.freedesktop.org/software/systemd/man/systemctl.html#--no-reload), `--no-reload` is not an option of the `preset` command.
Fix #2107 
> Fix installation of runtime rpm

- configs/next/packages/glibc/stage_1
- configs/next/packages/glibc/stage_2
- configs/next/packages/glibc/stage_optimized
The following issues have been fixed, preventing warnings to be thrown while building glibc:
- https://sourceware.org/bugzilla/show_bug.cgi?id=26647
- https://sourceware.org/bugzilla/show_bug.cgi?id=26686
- https://sourceware.org/bugzilla/show_bug.cgi?id=26687
Fix #1699 
> Remove some -Wno-error from glibc stages

- configs/14.0/packages/glibc/stage_optimized
Removed -Wno-error=maybe-uninitialized from glibc's stage_optimized on AT 14.0. It's no longer useful to prevent warnings to be thrown while building glibc.
Fix #1635
> Remove a -Wno-error flag from glibc's stage_optimized

- scripts/utilities/update_revision.sh
Use the '-s' parameter to include the 'Signed-off-by' line to auto-update
commits. If the user also specifies a GITHUB_SIGNATURE as the 5th argument to
update_revision.sh, the final commit will contain two separate signatures, the
one passed as argument and another for the Git user being used to create the
commit.
This allows us to create a commit that is both signed by our CI bot (Cherbot)
and another user, enabling auto-update PRs to properly pass the DCO check.
> Use git commit -s to sign auto-update commits

- configs/15.0/packages/binutils/sources
AT 15.0 will track the binutils-2_36-branch, whereas AT next will track the main branch.
> Move AT 15.0 to binutils branch binutils-2_36-branch

- scripts/utilities/update_revision.sh
Commit 465fed7 added support to mark our automated PRs as auto-mergeable, but missed 1 API
call. The code right after the changed line was still using the status code from
the previous REST API call to create the PR.
As a consequence, auto-merge was not being properly enabled on PRs.
> Add missing GraphQL API call to update_revision.sh

- configs/14.0/packages/gcc/sources
There has been an issue in GCC 10 whose fix depend on a patch already
available in GCC 11 and a patch for GCC 12 that are under review.
I've already asked for both patches to be backported.
Meanwhile, we may need to carry an extra patch in GCC 10.
> Add a patch to fix issue #2204

- configs/next/packages/python/sources
The current regex passed to sed on ATSRC_PACKAGE_UPSTREAM for Python on AT next
is not handling beta/alpha versions correctly (see #2249). Change it so that it
ignores any beta/alpha information and only output the main version.
> next: Fix regex to get current Python version

- scripts/utilities/update_revision.sh
The script handles tarball file as SVN URL causing inappropriate warnings.
This patch adds a check to verify if the given URL is a tarball or not, if not
it assumes it's a SVN URL.
Fix #2226 
> Fix update_revision.sh to handle tarball file

- configs/next/packages/binutils/stage_2
- configs/next/packages/gcc/sources
Bump to revision 2e345e4ad6bb
The libstdc++ gthreads fix has been merged upstream (commit 2e345e4ad6bb), so we
don't need to apply it anymore.
> Update GCC on AT next and remove out-of-tree patch

- configs/13.0/packages/gcc/stage_4
Some programs prefer to use the command f95 instead of gfortran.
Adding the symlink /opt/atX.Y/bin/f95 to the gfortran binary (X >= 13).
Fix #2281
> Add f95 symbolic link to gfortran

- configs/15.0/packages/tbb/sources
- configs/15.0/packages/tbb/stage_1
- fvtr/tbb/par-test.cpp
- scripts/helpers/utilities.mk
Bump to version 2021.3.0
Bump to revision 261fe22630bd
It diverges from AT 14.0 which tracks the branch tbb_2020.
AT next follows AT 15.0 until the creation of the 2022 branch.
> Update tbb on AT 15.0

- configs/15.0/base.mk
- configs/15.0/distros/debian-10.mk
- configs/15.0/distros/redhat-8.mk
- configs/15.0/distros/suse-15.mk
- configs/15.0/distros/ubuntu-20.mk
- configs/next/base.mk
Give a new interpretation to AT_KERNEL by moving it to base.mk.  Now,
it will be treated as the minimum kernel version supported by one AT
version.
This new interpretation will allow software built on a distro with a
newer kernel version to be executed on an older kernel version.
This is particularly more interesting when users start to run their
software inside containers whose host kernel may not be the same of the
distro inside the container.
> Move the definition of AT_KERNEL to base.mk on AT >= 15.0

- configs/15.0/packages/glibc/stage_1
- configs/15.0/packages/glibc/stage_2
- configs/15.0/packages/glibc/stage_optimized
- configs/next/packages/gcc/sources
A recent GCC update required further changes in GCC itself and in glibc.
One of the fix for a regression we caught a while ago has been merged, turning one of our patches obsolete. However, a new regression appeared and we need to revert 2 patches from upstream.
glibc requires 2 new `-Wno-error`. Luckily, 2 other parameters can be removed.
Close #2296.
> Update GCC and glibc on AT next

- configs/13.0/deb/monolithic/runtime.postinst
- configs/13.0/deb/monolithic/runtime.prerm
- configs/13.0/specs/monolithic.spec
- configs/14.0/specs/monolithic.spec
In packages scriplets, check that `systemctl` is available before using it.
This will avoid error messages when installing AT packages.
Fix #2330
> Verify `systemctl` is available before using it

- README.txt
- configs/13.0/distros/debian-10.mk
- configs/13.0/distros/redhat-8.mk
- configs/13.0/distros/suse-15.mk
- configs/13.0/distros/ubuntu-18.mk
- configs/14.0/distros/ubuntu-20.mk
GDB needs LZMA development packages during build to support
LZ-compressed debuginfo sections.  Without this support built-in,
GDB can report warnings like:
```
$ /opt/at15.0/bin/gdb /usr/bin/python3
[...]
Reading symbols from /usr/bin/python3...
warning: Cannot parse .gnu_debugdata section; LZMA support was disabled at compile time
(No debugging symbols found in /usr/bin/python3)
```
...and presumably reduced capability as a result.
A GDB that includes such support will report:
```
$ ./at-next-16.0-0-alpha/bin/gdb /usr/bin/python3
[...]
Reading symbols from /usr/bin/python3...
Reading symbols from .gnu_debugdata for /usr/libexec/platform-python3.6...
(No debugging symbols found in .gnu_debugdata for /usr/libexec/platform-python3.6)
[...]
```
(slightly better, at least.)
Fixes #1950. …
> Add LZMA development package as a prerequisite

- fvtr/gotools/gotools.exp
Running the FVTR test for `gotools` leaves a `go` directory in $HOME
because `go` creates and uses a workspace based on the environment
variable `GOPATH` or `$HOME/go` by default.
Set `GOPATH` to the FVTR directory for `gotools` instead.
> [FVTR] Set GOPATH to avoid creating $HOME/go

- configs/13.0/packages/python/stage_1
- configs/15.0/packages/python/stage_1
- configs/next/packages/python/python.mk
- configs/next/packages/python/stage_optimized
~~This is not ready to merge.~~
~~For one thing, it exposes a bug in GCC [PR 102107](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102107), which can result in Python crashing. The fix for this bug has only been committed to GCC trunk today.~~
~~Secondly, the results of the build would now be dependent on the system on which the build is performed.  On a Power9 system, a power9-optimized `libpython.so` is included in packages. On a Power10 system, a power9-optimized `libpython.so` and a power10-optmized `libpython.so` are included in packages. Preferably, "release-level" builds would be performed on a system with the latest processor, but failure to do so is silently ignored.~~
Also, the changes target "next". If deemed desirable, should they instead be targeted at "15.0"?
> Build and package optimized libpython.so

- fvtr/python/python.exp
Some Python tests have been failing intermittently for a while (#1873 and #2368),
most of (all?) the times on a single RHEL8 host we use for automated testing. We
have not been able to pinpoint the issue so far. But it could be related to high
system load as these tests are time-sensitive and are failing because of expired
timeouts. In most cases a simple rebuild makes the build pass.
This commit adds test_eintr and test_subprocess to the list of excluded tests,
at the cost of some test coverage.
Closes #1873
Closes #2368
> Disable some Python FVTR tests that fail intermittently

- configs/15.0/packages/binutils/sources
Bump to revision 2e62356d25e9
Removed backported patches.
Close #2401 
> Update binutils on AT 15.0

- configs/next/packages/valgrind/sources
Bump to revision 345edda43951
Removed a patch as bug 441506 has been fixed.
Close #2400 
> Update valgrind AT next

- configs/next/packages/gcc/sources
Bump to revision 2f3d43a35155.
The patch to remove the forced runpath when using --with-advance-toolchain has
been merged upstream as 9598134a055e9426fa283e51dac178d11af2c668, so we don't
need to apply it off-tree anymore.
Closes #2483
> Update gcc on AT next and stop applying patch

- configs/13.0/distros/debian-10.mk
- configs/13.0/distros/redhat-8.mk
- configs/13.0/distros/suse-15.mk
- configs/13.0/distros/ubuntu-18.mk
- configs/14.0/distros/ubuntu-20.mk
- configs/15.0/distros/debian-10.mk
- configs/15.0/distros/redhat-8.mk
- configs/15.0/distros/suse-15.mk
- configs/15.0/distros/ubuntu-20.mk
Since fda478d, subversion is no longer required to build AT >= 13.0.
Fix #2442
> Remove subversion from build requirement

- configs/15.0/packages/binutils/stage_2
- configs/next/packages/binutils/stage_2
The flag was disabled in 6ed6a47 to allow the tests `ck_ldds` and `systemtap` to pass.
Enabling back the flag.
Fix #2051
> Enable follow-debug-link in binutils on AT => 15.0

- configs/13.0/specs/release.spec
- configs/14.0/specs/release.spec
- configs/15.0/specs/release.spec
- configs/next/specs/release.spec
- fvtr/package-check/package-check.exp
- scripts/utilities/pkg_build_monolithic.sh
- utils/install_tools.sh
Added a spec file to build a -release package for SLES only.
This package provides information about a product, its repository, target distro, etc.
Fix #1372
> Provide -release package for SLES

- configs/15.0/packages/glibc/stage_1
- configs/15.0/packages/glibc/stage_2
- configs/15.0/packages/glibc/stage_optimized
- configs/next/packages/binutils/stage_2
b3ca16e and a46a9c8 added `-Wno-error=array-bounds` to glibc and binutils on AT next.
Removing it.
Fix #2243
> Remove array-bounds flag on AT next

- configs/next/packages/libnxz/sources
- configs/next/packages/libnxz/stage_1
Bump to revision 9fdc30c0cca8
libnxz has recently started using autoconf, so build commands had to be changed
accordingly.
Closes #2533
> Update libnxz on AT next

- fvtr/ck_ldds/ck_ldds.exp
- fvtr/systemtap/systemtap.exp
The exec command in Tcl treats output in stderror as errors, causing
false positive failures when a warning is printed.
> fvtr: Ignore stderror from readelf

- configs/11.0/packages/glibc/stage_1
Ignore errors that the SLES 12 compiler started to report.
> Fixes glibc_1 build for AT 12.0 on SLES 12

- configs/next/packages/libnxz/sources
update_revision.sh is still setting libnxz version to v0.61, even though v0.62
has been out for almost 6 months. Since the project now uses autoconf, we can
parse the AC_INIT string in configure.ac to properly get the latest version.
> Get the correct libnxz package version automatically

- fvtr/package-check/package-check.exp
While running fvtr test, don't check the `release` package (SUSE only) in cross build environment. The `release` package isn't available in cross build.
> Ignore SUSE `release` package on cross builds

- configs/15.0/packages/expat/sources
expat 2.4.3 has been released and will be distributed on AT 15.0.
AT next will continue to track expat master branch.
> Diverge expat on AT 15.0 from AT next

- configs/13.0/deb/monolithic/compat
- configs/13.0/deb/monolithic/rules
- configs/13.0/deb/monolithic_cross/compat
- configs/14.0/deb/monolithic/rules
- configs/15.0/deb/monolithic/rules
- configs/next/deb/monolithic/bullseye_dh_change_dest.patch
- configs/next/distros/debian-11.mk
- scripts/utilities/pkg_build_deb.sh
Note: removing libqt4-dev and dh-systemd from requirements as they're not available in Debian 11 at the moment.
Fix #2705 
> Add support of Debian 11 on AT next

- fvtr/python/python.exp
This test is known to fail if run on tmpfs on ppc64 [1]. It was fixed
for Python 3.8, which maps to AT 14, so it will fail for any versions
prior to that when tmpfs is used (like inside a container).
[1] https://bugs.python.org/issue35772
> Ignore test_tarfile Python test for older releases

- configs/15.0/packages/glibc/stage_2
Compile glibc with “user-defined-trusted-dirs” option to add
standard system libraries to paths that dynamic loader searchs for.
These paths will be the last in the order that dynamic loader will
look for( after  AT libraries paths )
Fixes issue #2888
Signed-off-by: Fabiane Watanabe <fabiane.watanabe@ibm.com>
> Fix installation fail of some packages in at-docker

- utils/install_tools.sh
`AT_BASE` is needed by some FVTR scripts, but `AT_BASE` is not defined when FVTR
scripts are called by the `install_tools.sh` script (with the `testsuite` command).
This patch set `AT_BASE` if it's not defined before running FVTR.
> Improve install_tools script

- Makefile
Today Make builds a tar.gz file with all the build logs by default, but
this is not always necessary/useful. Users that want to keep the same
behavior can use 'make collect' in addition to the normal build + test
steps from now on.
> Stop collecting logs by default

- configs/13.0/base.mk
- configs/13.0/specs/release.spec
- configs/14.0/base.mk
- configs/15.0/base.mk
- configs/16.0/base.mk
- fvtr/package-check/package-check.exp
- scripts/helpers/utilities.mk
- scripts/utilities/pkg_build_monolithic.sh
Updated the name of the product based on this comment[1].
The end of life in the spec file wasn't correct. Fixed this
and added an AT variable with the end of life for each AT version.
[1] https://bugzilla.linux.ibm.com/show_bug.cgi?id=193326#c11
> Fix the content of the release package (SLES)

- configs/next/base.mk
In 6e82c00a, the end of life date for AT next was missing.
Added it in this patch.
> Fix SLES release package for AT next

- configs/14.0/packages/groups
Created a group so `libnxz` will appear in the release notes.
Fix #2887 
> Add a group for libnxz

- configs/12.0/packages/golang/sources
- configs/12.0/packages/golang/stage_1
Start using golang 1.10.8 as the original compiler for building golang
on AT 12.0.
This fixes an issue that started to be reproduced on Linux 5.18 and was
fixed in golang 1.10.
> Update golang bootstrap version on AT 12.0

- configs/12.0/packages/boost/sources
- configs/13.0/packages/boost/sources
- configs/14.0/packages/boost/sources
- configs/15.0/packages/boost/sources
- configs/16.0/packages/boost/sources
The community is suggesting a different URL now from jfrog.io.
So, this commit adds the new URL without removing the previous one but
uses the new address with a higher priority than SourceForge.
> Add an extra URL for Boost's source code

- README.txt
In the `README.txt` there is an URL pointing to an IBM's private network.
This patch removes it.
Fix #2108
> Remove private URL from documentation

- configs/16.0/packages/zlib/sources
- configs/next/packages/zlib/sources
The recent 1.2.12 release brought some issues that were reported by
various zlib users (including other projects). Mark Adler has already
provided fixes for them, although only in the develop branch for now.
Apply the most important ones to AT 16.0 and next to guarantee we have
provide a working zlib to our users.
Fixes #3018
> Fix zlib issues on AT 16 and next

- configs/16.0/packages/openssl/stage_1
OpenSSL version 3.0 now handles parallelism well when building itself.
> Increase parallelism when building OpenSSL

- configs/13.0/deb/monolithic/runtime.postinst
- configs/13.0/deb/monolithic/runtime.prerm
- configs/14.0/specs/monolithic.spec
Podman/docker containers don't necessarily have systemd enabled so
AT installation on such systems fails when trying to setup the cachemanager
service. Simply don't try to setup the service when inside a container for now.
Signed-off-by: Fabiane Watanabe <fabiane.watanabe@ibm.com>
> Disable cachemanager service setup on containers

- configs/16.0/release_notes/release_notes-inst.html
Added missing installation guidelines for Debian 11, Ubuntu 22.04 and RHEL9 in the release notes.
Fix #3055
Also, replaced most of the GPG keys with a `xxxxxxxx` pattern. This pattern
is replaced with the appropriate GPG key value when generating the final
release notes.
In addition, rearranged the sections ; a fedora section was in middle of
ubuntu sections.
> Update installation guidelines

- configs/next/packages/zlib/sources
Bump to revision 04f42ceca40f
Got the power optimizations patches rebased on zlib 1.2.13. 
Removed the patches that were merged into zlib master branch.
> Update zlib on AT next

- configs/13.0/specs/release.spec
- fvtr/package-check/package-check.exp
Set the product name back to "advance-toolchain-at<VERSION>". 
Mark the product name "ibm-power-advance-toolchain" as obsolete so the SSC solver won't be lost.
Fix #3248 
Fix https://bugzilla.linux.ibm.com/show_bug.cgi?id=200754
> Fix the `release` package for Suse

- fvtr/shared.exp
Stop treating warnings from bash as errors in the FVTR (ck_ldds).
We only care about real errors, i.e. exit code != 0.
> Ignore bash warnings in FVTR (ck_ldds)

- configs/17.0/packages/glibc/sources
- configs/17.0/packages/glibc/stage_1
- configs/17.0/packages/glibc/stage_2
- configs/17.0/packages/glibc/stage_optimized
glibc 2.38 has been released and will be distributed on AT 17.0. AT next will continue to track glibc master branch.
> Diverge glibc on AT 17.0 from AT next

- configs/17.0/packages/glibc/sources
Backport a patch from the glibc main branch to the 2.38 branch. The patch enables the option to influence hwcaps used by PowerPC.
> Enable an option on glibc on AT 17.0

- fvtr/ck_provides/ck_provides.exp
- fvtr/ck_requires/ck_requires.exp
- fvtr/package-check/package-check.exp
- fvtr/shared.exp
The SHA-1 algorithm has deprecated for a while on RHEL9 [1]. The SHA-256 (or better) algorithm should be use to sign AT rpm packages.
Meanwhile a proper fix is provided, this patch ignores warning messages about the SHA-1 algorithm.
[1] https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9
> Add a workaround for SHA-1 issue on RHEL9

- fvtr/python/python.exp
Some python tests open an AF_UNIX socket. The AF_UNIX path is limited to 108 bytes[1].
In order to avoid error about a too long AF_UNIX path, the AT fvtr will be run in the /tmp directory.
[1] https://man7.org/linux/man-pages/man7/unix.7.html#BUGS
> Fix python fvtr issue

- configs/16.0/distros/redhat-9.mk
- configs/16.0/distros/ubuntu-22.mk
- configs/16.0/release_notes/relfixes.html
- configs/17.0/release_notes/relfixes.html
Set default processor to match with some distros requirement (RHEL9, and Ubuntu 22.04).
For these distros, the default build will be done using -mcpu=power9 instead of power8.
Fix #3152
Fix #3153
> Match default processor support from distro

- scripts/utilities/pkg_build_rpm.sh
On RHEL9 the script to collect debug information is not in the same directory as on RHEL8. This script is called when making the debug packages for AT.
With this patch, the correct file will used depending on the current RHEL version.
> Update rpm building script

- configs/14.0/packages/python/sources
- configs/15.0/packages/python/sources
- configs/16.0/packages/python/sources
- configs/17.0/packages/python/sources
- configs/next/packages/python/sources
On AT < 16.0 and AT next, update the patch about `zlib` version check.
On AT 16.0 and AT 17.0, remove the patch about `zlib` version check.
> Update python on AT

- configs/16.0/packages/glibc/sources
- configs/17.0/packages/glibc/sources
- configs/next/packages/glibc/sources
Disable the use of ldconfig aux-cache file on RHEL9. This will avoid ISA level error.
Fix #3844
Fix #3845
> Add a patch to disable ldconfig aux-cache file

- configs/18.0/packages/gcc/sources
- configs/next/packages/gcc/sources
AT 18.0 will track the gcc ibm/gcc-14-branch branch. AT next will track the gcc trunk (gcc 15).
> Move AT 18.0 to gcc branch ibm/gcc-14-branch

- configs/15.0/packages/gcc/sources
- configs/16.0/packages/gcc/sources
Add an external patch to skip glibc/pthread fix in GCC fixincludes.
> Fix related with fixincludes in AT <= 16.0

- fvtr/python/python.exp
Removed test_sundry from python tests. It imports a deprecated library.
Closes #4492 
Closes #4499 
Closes #4500
> Update python test in FVTR
